// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataStructure.proto

// Protobuf Java Version: 3.25.7
package com.hooniegit.DataStructure;

public interface BooleanTagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hooniegit.DataStructure.BooleanTag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>bool value = 2;</code>
   * @return The value.
   */
  boolean getValue();
}
