// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataStructure.proto

// Protobuf Java Version: 3.25.7
package com.hooniegit.DataStructure;

public interface BooleanGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hooniegit.DataStructure.BooleanGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.hooniegit.DataStructure.BooleanTag group = 1;</code>
   */
  java.util.List<com.hooniegit.DataStructure.BooleanTag> 
      getGroupList();
  /**
   * <code>repeated .com.hooniegit.DataStructure.BooleanTag group = 1;</code>
   */
  com.hooniegit.DataStructure.BooleanTag getGroup(int index);
  /**
   * <code>repeated .com.hooniegit.DataStructure.BooleanTag group = 1;</code>
   */
  int getGroupCount();
  /**
   * <code>repeated .com.hooniegit.DataStructure.BooleanTag group = 1;</code>
   */
  java.util.List<? extends com.hooniegit.DataStructure.BooleanTagOrBuilder> 
      getGroupOrBuilderList();
  /**
   * <code>repeated .com.hooniegit.DataStructure.BooleanTag group = 1;</code>
   */
  com.hooniegit.DataStructure.BooleanTagOrBuilder getGroupOrBuilder(
      int index);

  /**
   * <code>string timestamp = 2;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 2;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
