// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataStructure.proto

// Protobuf Java Version: 3.25.7
package com.hooniegit.DataStructure;

public final class DataStructure {
  private DataStructure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_DataStructure_IntegerTag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_DataStructure_IntegerTag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_DataStructure_DoubleTag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_DataStructure_DoubleTag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_DataStructure_StringTag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_DataStructure_StringTag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_DataStructure_BooleanTag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_DataStructure_BooleanTag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_DataStructure_IntegerGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_DataStructure_IntegerGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_DataStructure_DoubleGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_DataStructure_DoubleGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_DataStructure_StringGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_DataStructure_StringGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_DataStructure_BooleanGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_DataStructure_BooleanGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DataStructure.proto\022\033com.hooniegit.Dat" +
      "aStructure\"\'\n\nIntegerTag\022\n\n\002id\030\001 \001(\005\022\r\n\005" +
      "value\030\002 \001(\005\"&\n\tDoubleTag\022\n\n\002id\030\001 \001(\005\022\r\n\005" +
      "value\030\002 \001(\001\"&\n\tStringTag\022\n\n\002id\030\001 \001(\005\022\r\n\005" +
      "value\030\002 \001(\t\"\'\n\nBooleanTag\022\n\n\002id\030\001 \001(\005\022\r\n" +
      "\005value\030\002 \001(\010\"Y\n\014IntegerGroup\0226\n\005group\030\001 " +
      "\003(\0132\'.com.hooniegit.DataStructure.Intege" +
      "rTag\022\021\n\ttimestamp\030\002 \001(\t\"W\n\013DoubleGroup\0225" +
      "\n\005group\030\001 \003(\0132&.com.hooniegit.DataStruct" +
      "ure.DoubleTag\022\021\n\ttimestamp\030\002 \001(\t\"W\n\013Stri" +
      "ngGroup\0225\n\005group\030\001 \003(\0132&.com.hooniegit.D" +
      "ataStructure.StringTag\022\021\n\ttimestamp\030\002 \001(" +
      "\t\"Y\n\014BooleanGroup\0226\n\005group\030\001 \003(\0132\'.com.h" +
      "ooniegit.DataStructure.BooleanTag\022\021\n\ttim" +
      "estamp\030\002 \001(\tB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hooniegit_DataStructure_IntegerTag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hooniegit_DataStructure_IntegerTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_DataStructure_IntegerTag_descriptor,
        new java.lang.String[] { "Id", "Value", });
    internal_static_com_hooniegit_DataStructure_DoubleTag_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hooniegit_DataStructure_DoubleTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_DataStructure_DoubleTag_descriptor,
        new java.lang.String[] { "Id", "Value", });
    internal_static_com_hooniegit_DataStructure_StringTag_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hooniegit_DataStructure_StringTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_DataStructure_StringTag_descriptor,
        new java.lang.String[] { "Id", "Value", });
    internal_static_com_hooniegit_DataStructure_BooleanTag_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hooniegit_DataStructure_BooleanTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_DataStructure_BooleanTag_descriptor,
        new java.lang.String[] { "Id", "Value", });
    internal_static_com_hooniegit_DataStructure_IntegerGroup_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_hooniegit_DataStructure_IntegerGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_DataStructure_IntegerGroup_descriptor,
        new java.lang.String[] { "Group", "Timestamp", });
    internal_static_com_hooniegit_DataStructure_DoubleGroup_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_hooniegit_DataStructure_DoubleGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_DataStructure_DoubleGroup_descriptor,
        new java.lang.String[] { "Group", "Timestamp", });
    internal_static_com_hooniegit_DataStructure_StringGroup_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_hooniegit_DataStructure_StringGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_DataStructure_StringGroup_descriptor,
        new java.lang.String[] { "Group", "Timestamp", });
    internal_static_com_hooniegit_DataStructure_BooleanGroup_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_hooniegit_DataStructure_BooleanGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_DataStructure_BooleanGroup_descriptor,
        new java.lang.String[] { "Group", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
