// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataStructure.proto

// Protobuf Java Version: 3.25.7
package com.hooniegit.DataStructure;

public interface StringGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hooniegit.DataStructure.StringGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.hooniegit.DataStructure.StringTag group = 1;</code>
   */
  java.util.List<com.hooniegit.DataStructure.StringTag> 
      getGroupList();
  /**
   * <code>repeated .com.hooniegit.DataStructure.StringTag group = 1;</code>
   */
  com.hooniegit.DataStructure.StringTag getGroup(int index);
  /**
   * <code>repeated .com.hooniegit.DataStructure.StringTag group = 1;</code>
   */
  int getGroupCount();
  /**
   * <code>repeated .com.hooniegit.DataStructure.StringTag group = 1;</code>
   */
  java.util.List<? extends com.hooniegit.DataStructure.StringTagOrBuilder> 
      getGroupOrBuilderList();
  /**
   * <code>repeated .com.hooniegit.DataStructure.StringTag group = 1;</code>
   */
  com.hooniegit.DataStructure.StringTagOrBuilder getGroupOrBuilder(
      int index);

  /**
   * <code>string timestamp = 2;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 2;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
