// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataStructure.proto

// Protobuf Java Version: 3.25.7
package com.hooniegit.DataStructure.Protobuf;

public interface DoubleTagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hooniegit.DataStructure.Protobuf.DoubleTag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>double value = 2;</code>
   * @return The value.
   */
  double getValue();
}
