// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataStructure.proto

// Protobuf Java Version: 3.25.7
package com.hooniegit.DataStructure.Protobuf;

public interface IntegerGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hooniegit.DataStructure.Protobuf.IntegerGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.hooniegit.DataStructure.Protobuf.IntegerTag group = 1;</code>
   */
  java.util.List<IntegerTag>
      getGroupList();
  /**
   * <code>repeated .com.hooniegit.DataStructure.Protobuf.IntegerTag group = 1;</code>
   */
  IntegerTag getGroup(int index);
  /**
   * <code>repeated .com.hooniegit.DataStructure.Protobuf.IntegerTag group = 1;</code>
   */
  int getGroupCount();
  /**
   * <code>repeated .com.hooniegit.DataStructure.Protobuf.IntegerTag group = 1;</code>
   */
  java.util.List<? extends IntegerTagOrBuilder>
      getGroupOrBuilderList();
  /**
   * <code>repeated .com.hooniegit.DataStructure.Protobuf.IntegerTag group = 1;</code>
   */
  IntegerTagOrBuilder getGroupOrBuilder(
      int index);

  /**
   * <code>string timestamp = 2;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 2;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
