// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataStructure.proto

// Protobuf Java Version: 3.25.7
package com.hooniegit.DataStructure.Protobuf;

public interface IntegerTagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hooniegit.DataStructure.Protobuf.IntegerTag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 value = 2;</code>
   * @return The value.
   */
  int getValue();
}
